INSERT INTO specialties (name, description)
VALUES
    ('Cardiologia', 'Especialidade responsável pelo coração'),
    ('Neurologia', 'Especialidade responsável pelo sistema nervoso'),
    ('Ortopedia', 'Especialidade responsável pelo sistema musculoesquelético'),
    ('Clínica Geral', 'Atendimento clínico geral'),
    ('Pediatria', 'Cuidados médicos para crianças e adolescentes'),
    ('Ginecologia', 'Saúde do sistema reprodutor feminino'),
    ('Obstetrícia', 'Acompanhamento de gestação e parto'),
    ('Dermatologia', 'Diagnóstico e tratamento da pele, cabelos e unhas'),
    ('Oftalmologia', 'Cuidados com a visão e os olhos'),
    ('Otorrinolaringologia', 'Tratamento de ouvido, nariz e garganta'),
    ('Psiquiatria', 'Avaliação e tratamento da saúde mental'),
    ('Endocrinologia', 'Tratamento de hormônios e metabolismo'),
    ('Gastroenterologia', 'Cuidados com sistema digestivo'),
    ('Pneumologia', 'Tratamento de doenças respiratórias'),
    ('Urologia', 'Cuidados com trato urinário e sistema reprodutor masculino'),
    ('Nefrologia', 'Tratamento dos rins e funções renais'),
    ('Reumatologia', 'Diagnóstico e tratamento de doenças autoimunes e articulares'),
    ('Infectologia', 'Tratamento de doenças infecciosas'),
    ('Hematologia', 'Cuidados com o sangue e seus componentes'),
    ('Oncologia', 'Tratamento de câncer'),
    ('Vascular', 'Tratamento de vasos sanguíneos'),
    ('Cirurgia Geral', 'Avaliação e procedimentos cirúrgicos gerais'),
    ('Anestesiologia', 'Assistência anestésica e controle de dor'),
    ('Neuropediatria', 'Cuidados neurológicos especializados em crianças'),
    ('Mastologia', 'Cuidados com as mamas'),
    ('Nutrologia', 'Avaliação nutricional e suporte ao tratamento')
ON CONFLICT (name) DO NOTHING;
